### PR TITLE
Guarantee address in `slice()` for empty slices.

### LINKED ISSUE #779: Preserve addresses of empty bytes in `slice`
I would like to use `Bytes` to create parsers for binary formats. To report precise error messages, I would like to rely on `Bytes::as_ptr() as usize` to get the current position in the main file. That works quite well ... except for when I run out of input. Consider the following example:

~~~ rust
    let b = Bytes::from_owner(b"Hi");
    for i in 0..=b.len() {
        let s = b.slice(i..);
        let offset = dbg!(dbg!(s.as_ptr() as usize) - dbg!(b.as_ptr() as usize));
    }
~~~

Here, the output is:

~~~
[src/main.rs:16:27] s.as_ptr() as usize = 101899852842091
[src/main.rs:16:55] b.as_ptr() as usize = 101899852842091
[src/main.rs:16:22] dbg!(s.as_ptr() as usize) - dbg!(b.as_ptr() as usize) = 0
[src/main.rs:16:27] s.as_ptr() as usize = 101899852842092
[src/main.rs:16:55] b.as_ptr() as usize = 101899852842091
[src/main.rs:16:22] dbg!(s.as_ptr() as usize) - dbg!(b.as_ptr() as usize) = 1
[src/main.rs:16:27] s.as_ptr() as usize = 1             <---------------------------------- !
[src/main.rs:16:55] b.as_ptr() as usize = 101899852842091
thread 'main' panicked at src/main.rs:16:27:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~~~

We can see that an empty `Bytes` loses its offset. This is caused by the [following code in `Bytes::slice`](https://github.com/tokio-rs/bytes/blob/141cbc22cbd04c4f3cf3d2af0a0f449322918d69/src/bytes.rs#L403C19-L405C10):

~~~ rust
        if end == begin {
            return Bytes::new();
        }
~~~

This code also contradicts the current documentation for `Bytes::slice`, which states:

> This will increment the reference count for the underlying memory and return a new Bytes handle set to the slice.

I would like to propose the removal of the `end == begin` check. Why?
Without this check in `Bytes::slice`, a user of `Bytes` can get the effect of this check by just doing the check manually before running `Bytes::slice`. However, with this check in `Bytes::slice`, it is impossible to disable it. Also, without this check, the behaviour of the function would automatically correspond to its documentation, which is currently not the case.

### PR DESCRIPTION
**Pull request by 01mf02**
This should close #779.

### CODE REVIEW

File: src/bytes.rs [hunk 1]
```diff
@@ -400,10 +400,6 @@ impl Bytes {
             len,
         );
 
-        if end == begin {
-            return Bytes::new();
-        }
```
Comment (Darksonn) [inline src/bytes.rs:405]: Right now, the `Bytes` instance is going to hold a refcount to the allocation, which is not necessary. Please go through `new_empty_with_ptr` instead.

Comment (01mf02) [reply src/bytes.rs]: I see, this is a very nifty technique! That means that in principle, you could have `b1: Bytes` at address `a`, take an empty slice via `let s1 = b1.slice(..0)`, then have `b1` destroyed. Next, you could have `b2: Bytes ` at the *same* address `a`, and take another empty slice via `let s2 = b2.slice(..0)`. The two slices `s1` and `s2` came from different Bytes, yet share the same address. I thought that this would be a problem, but it isn't, because `s1` and `s2`  are empty anyway.
Cool stuff!

**Review by Darksonn — APPROVED** [review]
Thanks. Sorry about the delay.

**Comment by 01mf02** [comment]
Don't worry. Thanks for merging it. :)
