### PR TITLE
Fix Bytes when Vec pointer's LSB is set

### LINKED ISSUE #343: Bytes assumes that Vec<u8>'s allocation is more than 1 byte aligned
It uses the low bit of the pointer to distinguish between KIND_VEC and KIND_ARC.

Folded over from #340

### PR DESCRIPTION
**Pull request by seanmonstar**
This separates the `SharedVtable` into 3:

- `PromotableEvenVtable`: The original `SharedVtable`, which will
  promote the `Vec` to `Shared` on the first clone, and is selected when
  the `Vec`'s pointer has the LSB unset.
- `PromotableOddVtable`: Similar to the `PromotableEvenVtable`, but
  selected when the `Vec`'s pointer has the LSB set. This vtable differs
  in the masking used when reconstructing the `Vec`.
- `SharedVtable`: This no longer checks if its current kind is `VEC` or
  `ARC`, and is only created by the "promotable" vtables.

This also adds a test using an "odd" global allocator that purposefully
bumps all pointers with alignment of 1.

Closes #343

### CODE REVIEW

File: src/bytes.rs [hunk 1]
```diff
@@ -731,20 +731,23 @@ impl From<Vec<u8>> for Bytes {
         let slice = vec.into_boxed_slice();
```
Comment (sfackler) [inline src/bytes.rs]: The is_empty special case above can be removed now that the low bit is being tracked properly.

File: src/bytes.rs [hunk 2]
```diff
@@ -782,50 +785,71 @@ unsafe fn static_drop(_: &mut AtomicPtr<()>, _: *const u8, _: usize) {
...
         debug_assert_eq!(kind, KIND_VEC);
 
-        drop(rebuild_vec(shared, ptr, len));
+        drop(rebuild_vec(shared as *mut u8, ptr, len));
     }
 }
 
-unsafe fn rebuild_vec(shared: *const (), offset: *const u8, len: usize) -> Vec<u8> {
+unsafe fn rebuild_vec(buf: *mut u8, offset: *const u8, len: usize) -> Vec<u8> {
+    /*
```
Comment (sfackler) [inline src/bytes.rs]: dead code
