### PR TITLE
Fix Bytes::truncate losing the original Vec's capacity

### LINKED ISSUE #360: Bytes may recreate Vec incorrectly on drop
This example:

```
diff --git a/examples/rrr.rs b/examples/rrr.rs
index e69de29..60374de 100644
--- a/examples/rrr.rs
+++ b/examples/rrr.rs
@@ -0,0 +1,7 @@
+use bytes::Bytes;
+
+fn main() {
+    let mut bytes = Bytes::from(vec![10, 20, 30]);
+    bytes.truncate(2);
+    drop(bytes);
+}
diff --git a/src/bytes.rs b/src/bytes.rs
index 93ab84b..6af5148 100644
--- a/src/bytes.rs
+++ b/src/bytes.rs
@@ -767,6 +767,7 @@ impl From<Vec<u8>> for Bytes {
         let slice = vec.into_boxed_slice();
         let len = slice.len();
         let ptr = slice.as_ptr();
+        println!("dismantling a vec of cap {}", len);
         drop(Box::into_raw(slice));
 
         if ptr as usize & 0x1 == 0 {
@@ -886,6 +887,7 @@ unsafe fn promotable_odd_drop(data: &mut AtomicPtr<()>, ptr: *const u8, len: usi
 
 unsafe fn rebuild_vec(buf: *mut u8, offset: *const u8, len: usize) -> Vec<u8> {
     let cap = (offset as usize - buf as usize) + len;
+    println!("rebuilding vec with cap {}", cap);
     Vec::from_raw_parts(buf, cap, cap)
 }
 
diff --git a/src/lib.rs b/src/lib.rs
index 2df1fb3..5d9355b 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,6 +1,5 @@
 #![deny(warnings, missing_docs, missing_debug_implementations, rust_2018_idioms)]
 #![doc(html_root_url = "https://docs.rs/bytes/0.5.3")]
-#![no_std]
 
 //! Provides abstractions for working with bytes.
 //!
```

```
% cargo run --example rrr
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/rrr`
dismantled a vec of cap 3
rebuilding vec with cap 2
```

So we are allocating 3 * 4 bytes, but when calling deallocation we are passing hint parameter 2 * 4 which causes deallocation by `RawVec` which calls `GlobalAlloc.dealloc` which violates the spec: ("layout must be the same layout that was used to allocate that block of memory").

I suspect it may crash deallocation or cause memory leaks, although I could not reproduce either.

I tried this program:

```
#[global_allocator]
static ALLOC: jemallocator::Jemalloc = jemallocator::Jemalloc;

use bytes::Bytes;

fn main() {
    loop {
        let mut bytes = Bytes::from(vec![10; 100000000]);
        bytes.truncate(1);
        drop(bytes);
    }
}
```

After a few seconds of run, macOS Activity Monitor shows 100Gb of memory usage by this program which is a sign that something doesn't work as expected.

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #360

### CODE REVIEW

File: src/bytes.rs [hunk 1]
```diff
@@ -418,7 +418,15 @@ impl Bytes {
     #[inline]
     pub fn truncate(&mut self, len: usize) {
         if len < self.len {
-            self.len = len;
+            // The Vec "promotable" vtables do not store the capacity,
+            // so we cannot truncate while using this repr. We *have* to
+            // promote using `split_off` so the capacity can be stored.
+            if self.vtable as *const Vtable == &PROMOTABLE_EVEN_VTABLE ||
+                self.vtable as *const Vtable == &PROMOTABLE_ODD_VTABLE {
+                drop(self.split_off(len));
```
Comment (udoprog) [inline src/bytes.rs]: Might want to consider implementing this by using `clone` directly?
```rust
*self = self.clone();
self.len = len;
```
Which should accomplish the upgrade in-place (and update the local vtable to boot), while avoiding any extra work associated with `split_off`.

Comment (stepancheg) [reply src/bytes.rs]: `clone()` will be less efficient at `truncate(0)`.

**Comment by carllerche** [comment]
We probably should merge this as is for now. It is unfortunate that this requires knowledge of the vtable in truncate.

I think there are ways to improve this in the future, but at least we can do this for now i guess!
